<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ThisIsMyPC.Core\ThisIsMyPC.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data\catalog.json" LogicalName="ThisIsMyPC.Modules.Software.Data.catalog.json" />
    <EmbeddedResource Include="Data\windows-apps.json" LogicalName="ThisIsMyPC.Modules.Software.Data.windows-apps.json" />
  </ItemGroup>
</Project>
