<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" /><PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" /><PackageReference Include="xunit.runner.visualstudio" />
    <Using Include="Xunit" />
    <ProjectReference Include="..\..\src\ThisIsMyPC.Modules.Network\ThisIsMyPC.Modules.Network.csproj" />
    <ProjectReference Include="..\..\src\ThisIsMyPC.Interop.Win32\ThisIsMyPC.Interop.Win32.csproj" />
    <ProjectReference Include="..\..\src\ThisIsMyPC.Interop.Com\ThisIsMyPC.Interop.Com.csproj" />
  </ItemGroup>
</Project>
