"""Generate Avalonia geometry from the vendored Microsoft Fluent SVG subset."""
from pathlib import Path
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parent.parent
source = root / "assets/fluent-system-icons"
target = root / "src/ThisIsMyPC.App/Icons"
entries = []
for file in sorted(source.glob("*.svg")):
    name, variant = file.stem.removeprefix("ic_fluent_").split("_20_")
    symbol = "".join(part.title() for part in name.split("_"))
    svg = ET.parse(file).getroot()
    assert svg.attrib["viewBox"] == "0 0 20 20", file
    assert all(node.tag.endswith("}path") for node in svg), file
    assert all(node.get("fill-rule", "nonzero") == "nonzero" and "transform" not in node.attrib for node in svg), file
    path = " ".join(node.attrib["d"] for node in svg)
    entries.append((symbol, variant == "filled", path))
symbols = sorted({symbol for symbol, _, _ in entries})
header = "// Generated by tools/generate-fluent-icons.py. Microsoft MIT license: assets/fluent-system-icons/LICENSE.\n"
(target / "FluentSymbol.cs").write_text(header + "namespace ThisIsMyPC.App.Icons;\n\npublic enum FluentSymbol\n{\n" + "".join(f"    {symbol},\n" for symbol in symbols) + "}\n", encoding="utf-8")
lines = [f'        [(FluentSymbol.{symbol}, {str(filled).lower()})] = Geometry.Parse("F1 {path}"),' for symbol, filled, path in entries]
(target / "FluentIconData.cs").write_text(header + "using Avalonia.Media;\n\nnamespace ThisIsMyPC.App.Icons;\n\ninternal static class FluentIconData\n{\n    private static readonly Dictionary<(FluentSymbol, bool), Geometry> Paths = new()\n    {\n" + "\n".join(lines) + "\n    };\n\n    public static Geometry Get(FluentSymbol symbol, bool filled) =>\n        Paths.GetValueOrDefault((symbol, filled)) ?? Paths[(symbol, false)];\n}\n", encoding="utf-8")
