# Turns OpenRGB's REGISTER_I2C_PCI_DETECTOR lines into a C# detector table for
# one ported controller family. Reads the controller's *Detect.cpp and OpenRGB's
# pci_ids.h (both fetched by tools/fetch-openrgb-controller.ps1), keeps the
# lines that name the given detector function, resolves every id macro, and
# writes a static class with one I2cPciDetector per line, in file order.
# The generated file is committed; re-run it to pull new device ids.
# Usage:
#   .\tools\import-openrgb-pci-detectors.ps1 -DetectSource <ENESMBusControllerDetect.cpp> `
#       -PciIds <pci_ids.h> -DetectorFunction DetectENESMBusGPUControllers `
#       -ClassName EneGpuDetectors -Namespace ThisIsMyPC.Lighting.Controllers.Ene `
#       -DetectMethod EneGpuDetectors.DetectGpu -Output src\ThisIsMyPC.Lighting\Controllers\Ene\EneGpuDetectors.g.cs
param(
    [Parameter(Mandatory)][string]$DetectSource,
    [Parameter(Mandatory)][string]$PciIds,
    [Parameter(Mandatory)][string]$DetectorFunction,
    [Parameter(Mandatory)][string]$ClassName,
    [Parameter(Mandatory)][string]$Namespace,
    [Parameter(Mandatory)][string]$DetectMethod,
    [Parameter(Mandatory)][string]$Output,
    [string]$SourceRevision = ''
)

$ErrorActionPreference = 'Stop'
$Output = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Output)

$ids = @{}
foreach ($line in Get-Content -LiteralPath $PciIds) {
    if ($line -match '^\s*#define\s+(\w+)\s+(0x[0-9A-Fa-f]+|\d+)') {
        $ids[$matches[1]] = [int]$matches[2]
    }
}

function Resolve-Id([string]$token) {
    $token = $token.Trim()
    if ($token -match '^0x[0-9A-Fa-f]+$' -or $token -match '^\d+$') { return [int]$token }
    if ($ids.ContainsKey($token)) { return $ids[$token] }
    throw "Unknown id macro '$token'; is pci_ids.h current?"
}

$entries = New-Object System.Collections.Generic.List[string]
foreach ($line in Get-Content -LiteralPath $DetectSource) {
    if ($line -notmatch '^\s*REGISTER_I2C_PCI_DETECTOR\s*\(\s*"([^"]+)"\s*,\s*(\w+)\s*,\s*([^,]+),\s*([^,]+),\s*([^,]+),\s*([^,]+),\s*([^)]+)\)') { continue }
    if ($matches[2] -ne $DetectorFunction) { continue }
    $name = $matches[1]
    $vendor = Resolve-Id $matches[3]
    $device = Resolve-Id $matches[4]
    $subVendor = Resolve-Id $matches[5]
    $subDevice = Resolve-Id $matches[6]
    $address = Resolve-Id $matches[7]
    $entries.Add(('        new("{0}", 0x{1:X4}, 0x{2:X4}, 0x{3:X4}, 0x{4:X4}, 0x{5:X2}, {6}),' -f $name, $vendor, $device, $subVendor, $subDevice, $address, $DetectMethod))
}
if ($entries.Count -eq 0) { throw "No REGISTER_I2C_PCI_DETECTOR lines call $DetectorFunction in $DetectSource" }

$revision = if ($SourceRevision) { " at $SourceRevision" } else { '' }
$content = @"
// <auto-generated>
// Generated by tools/import-openrgb-pci-detectors.ps1 from OpenRGB's
// $(Split-Path -Leaf $DetectSource) ($DetectorFunction)$revision and pci_ids.h.
// Do not edit; re-run the script to pull new device ids.
// </auto-generated>
using ThisIsMyPC.Lighting.Detection;

namespace $Namespace;

public static partial class $ClassName
{
    /// <summary>Every PCI id OpenRGB routes to $DetectorFunction, in its order.</summary>
    public static IReadOnlyList<I2cPciDetector> I2cPci { get; } =
    [
$($entries -join "`n")
    ];
}
"@

$directory = Split-Path -Parent $Output
if ($directory -and -not (Test-Path -LiteralPath $directory)) { New-Item -ItemType Directory -Path $directory -Force | Out-Null }
[IO.File]::WriteAllText($Output, $content.Replace("`r`n", "`n"), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $($entries.Count) detectors to $Output"
